import React, { useState } from 'react';
import { Button, Modal, Tag, CodeSnippet, Loading, TextInput } from '@carbon/react';
import { CheckmarkFilled, Restart } from '@carbon/icons-react';
import { GENERATED_YAML, PR_DETAILS } from '../data/demo-data';
import { api, FixResponse, PRResponse } from '../services/api';

interface TreatSectionProps {
  fixData: FixResponse | null;
  onPRComplete: (data: PRResponse) => void;
  prData: PRResponse | null;
  onRestart: () => void;
}

type TreatState = 'review' | 'confirming' | 'success';

/**
 * PHASE 4 - TREAT
 * Generated artifact preview + approval gate + success state.
 * The approval gate is intentional - reinforces the human-in-the-loop
 * differentiator and IBM's enterprise-trust positioning.
 */
const TreatSection: React.FC<TreatSectionProps> = ({
  fixData,
  onPRComplete,
  prData,
  onRestart
}) => {
  const [state, setState] = useState<TreatState>('review');
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [repository, setRepository] = useState('');

  const handleApprove = () => setState('confirming');
  
  const handleConfirm = async () => {
    if (!fixData || !repository) {
      setError('Please enter a repository name (e.g., owner/repo)');
      return;
    }
    
    setLoading(true);
    setError(null);
    
    try {
      const result = await api.createPR({
        fix_id: fixData.fix_id,
        repository: repository,
        branch: 'optimization/workflow-improvements',
        title: 'Optimize CI/CD workflow',
        description: 'Automated workflow optimization generated by ProcessDoctor',
      });
      
      onPRComplete(result);
      setState('success');
    } catch (err: any) {
      setError(err.message || 'Failed to create pull request');
      console.error('PR creation error:', err);
      setState('review');
    } finally {
      setLoading(false);
    }
  };

  if (loading) {
    return (
      <section style={{ paddingTop: 'var(--pd-space-07)', textAlign: 'center' }}>
        <Loading description="Creating pull request..." withOverlay={false} />
        <h2 style={{ marginTop: 'var(--pd-space-06)' }}>Creating pull request...</h2>
        <p className="pd-text-secondary" style={{ marginTop: 'var(--pd-space-03)' }}>
          Bob is opening a pull request with the optimized workflow.
        </p>
      </section>
    );
  }

  if (state === 'success' && prData) {
    return (
      <section
        style={{
          paddingTop: 'var(--pd-space-09)',
          paddingBottom: 'var(--pd-space-09)',
          textAlign: 'center',
        }}
      >
        <div style={{ maxWidth: '560px', margin: '0 auto' }}>
          <CheckmarkFilled
            size={64}
            style={{ color: 'var(--pd-color-success)', marginBottom: 'var(--pd-space-06)' }}
          />
          <h2 style={{ marginBottom: 'var(--pd-space-04)' }}>Pull request created</h2>
          <p
            style={{
              fontSize: 'var(--pd-font-size-body-lg)',
              color: 'var(--pd-color-text-secondary)',
              marginBottom: 'var(--pd-space-08)',
            }}
          >
            Your team will be notified. Bob will monitor execution and surface any issues for re-optimization.
          </p>

          <article
            style={{
              textAlign: 'left',
              padding: 'var(--pd-space-06)',
              border: '1px solid var(--pd-color-border-subtle)',
              background: 'var(--pd-color-surface)',
              borderRadius: 'var(--pd-radius-sm)',
              marginBottom: 'var(--pd-space-08)',
            }}
          >
            <div
              style={{
                fontSize: 'var(--pd-font-size-label)',
                color: 'var(--pd-color-text-secondary)',
                marginBottom: 'var(--pd-space-02)',
              }}
            >
              Repository
            </div>
            <div
              style={{
                fontSize: 'var(--pd-font-size-heading-03)',
                fontWeight: 'var(--pd-font-weight-medium)',
                marginBottom: 'var(--pd-space-04)',
              }}
            >
              {prData.pr_url ? (
                <a href={prData.pr_url} target="_blank" rel="noopener noreferrer">
                  View Pull Request #{prData.pr_number}
                </a>
              ) : (
                `Pull Request #${prData.pr_number}`
              )}
            </div>
            <div style={{ display: 'flex', gap: 'var(--pd-space-03)', flexWrap: 'wrap' }}>
              <Tag type="green">PR #{prData.pr_number} opened</Tag>
              <Tag type="blue">{prData.branch}</Tag>
            </div>
          </article>

          <Button kind="tertiary" renderIcon={Restart} onClick={onRestart}>
            Diagnose another workflow
          </Button>
        </div>
      </section>
    );
  }

  // Get generated YAML from fix data or use demo data
  const generatedYaml = fixData?.optimized_workflow
    ? JSON.stringify(fixData.optimized_workflow, null, 2)
    : GENERATED_YAML;

  return (
    <section style={{ paddingTop: 'var(--pd-space-07)' }}>
      {error && (
        <div style={{ marginBottom: 'var(--pd-space-06)', padding: 'var(--pd-space-05)', background: 'var(--pd-color-error-subtle)', border: '1px solid var(--pd-color-error-border)', borderRadius: 'var(--pd-radius-sm)' }}>
          <Tag type="red">Error</Tag>
          <p style={{ marginTop: 'var(--pd-space-03)', color: 'var(--pd-color-error)' }}>{error}</p>
        </div>
      )}
      <div style={{ marginBottom: 'var(--pd-space-07)' }}>
        <Tag type="blue">Ready for approval</Tag>
        <h2 style={{ marginTop: 'var(--pd-space-04)', marginBottom: 'var(--pd-space-03)' }}>
          Treatment: generated CI/CD pipeline
        </h2>
        <p className="pd-text-secondary">
          Bob has generated the optimized GitHub Actions workflow. Review the file before we open the pull request.
        </p>
      </div>

      {/* Generated YAML preview */}
      <h3 style={{ marginBottom: 'var(--pd-space-04)' }}>
        Generated file: .github/workflows/ci.yml
      </h3>
      <CodeSnippet type="multi" feedback="Copied">
        {generatedYaml}
      </CodeSnippet>

      {/* PR preview card */}
      <div style={{ marginTop: 'var(--pd-space-07)' }}>
        <h3 style={{ marginBottom: 'var(--pd-space-04)' }}>Pull request preview</h3>
        <article
          style={{
            padding: 'var(--pd-space-06)',
            border: '1px solid var(--pd-color-border-subtle)',
            background: 'var(--pd-color-background)',
            borderRadius: 'var(--pd-radius-sm)',
          }}
        >
          <div
            style={{
              fontSize: 'var(--pd-font-size-label)',
              color: 'var(--pd-color-text-secondary)',
              marginBottom: 'var(--pd-space-02)',
            }}
          >
            {PR_DETAILS.repository}
          </div>
          <div
            style={{
              fontSize: 'var(--pd-font-size-heading-03)',
              fontWeight: 'var(--pd-font-weight-medium)',
              marginBottom: 'var(--pd-space-03)',
            }}
          >
            {PR_DETAILS.title}
          </div>
          <p className="pd-text-secondary" style={{ marginBottom: 'var(--pd-space-04)' }}>
            {PR_DETAILS.description}
          </p>
          <div style={{ display: 'flex', gap: 'var(--pd-space-03)', flexWrap: 'wrap' }}>
            <Tag type="blue">{PR_DETAILS.branch}</Tag>
            <Tag type="gray">+{PR_DETAILS.additions} −{PR_DETAILS.deletions}</Tag>
            <Tag type="purple">Generated by ProcessDoctor</Tag>
          </div>
        </article>
      </div>

      {/* Repository input */}
      <div style={{ marginTop: 'var(--pd-space-07)' }}>
        <TextInput
          id="repository-input"
          labelText="GitHub Repository"
          placeholder="owner/repo (e.g., octocat/hello-world)"
          value={repository}
          onChange={(e) => setRepository(e.target.value)}
          helperText="Enter the repository where you want to create the pull request"
        />
      </div>

      <div
        style={{
          marginTop: 'var(--pd-space-05)',
          display: 'flex',
          gap: 'var(--pd-space-04)',
          justifyContent: 'flex-end',
        }}
      >
        <Button kind="tertiary" onClick={onRestart}>Cancel</Button>
        <Button
          kind="primary"
          size="lg"
          onClick={handleApprove}
          disabled={!repository}
        >
          Approve and deploy
        </Button>
      </div>

      {/* Confirmation modal — explicit human-in-the-loop gate */}
      <Modal
        open={state === 'confirming'}
        modalHeading="Approve treatment?"
        primaryButtonText="Yes, open pull request"
        secondaryButtonText="Cancel"
        onRequestClose={() => setState('review')}
        onRequestSubmit={handleConfirm}
        size="sm"
      >
        <p>
          This will open a pull request in <strong>{repository || 'your repository'}</strong> on
          branch <strong>optimization/workflow-improvements</strong>. The pipeline change does not deploy
          automatically — your team must merge the PR before the new workflow takes effect.
        </p>
        <p style={{ marginTop: 'var(--pd-space-04)', fontSize: 'var(--pd-font-size-body-sm)', color: 'var(--pd-color-text-secondary)' }}>
          Note: Your GitHub token must have write access to this repository.
        </p>
      </Modal>
    </section>
  );
};

export default TreatSection;
